package templates

import "text/template"

var TplDTO = template.Must(template.New("").Parse(`// Code generated by github.com/slasyz/openrest DO NOT EDIT.
package generated

{{ range .Structs}}
type {{.Name}} struct {
{{ range .Fields}}
    {{.Name}} {{.Type -}}
{{end}}
}
{{end}}
`))
